

ui:
  image: guimard/UI
  ports:
    - "8080:8080"
  links:
    - helloworldservice
    - guestbookservice
    - redis

helloworldservice:
  image: guimard/echo-service

guestbookservice:
  image: guimard/echo-service
  ports:
    - "8888:8080"
  links:
    - mysql

mysql:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: yourpassword
    MYSQL_DATABASE: app

redis:
  image: redis
